[env]
TERM = "xterm-256color"

[general]
import = [
  "C:/Users/itinerario/Documents/leo/development/dotfiles/home/.config/alacritty/themes/themes/doom_one.toml",
]

[font]
normal = { family = "JetBrainsMono NF" }
bold = { family = "JetBrainsMono NF" }
italic = { family = "JetBrainsMono NF" }
# normal = { family = "JetBrainsMono Nerd Font Mono" }
# bold = { family = "JetBrainsMono Nerd Font Mono" }
# italic = { family = "JetBrainsMono Nerd Font Mono" }
size = 10

[window]
padding.x = 7
padding.y = 7
decorations = "None"

[keyboard]
bindings = [
  { key = "Insert", mods = "Shift", action = "Paste" },
  { key = "Insert", mods = "Control", action = "Copy" },
]

[terminal]
osc52 = "CopyPaste"
